on:
  schedule:
    - cron: "0 18 * * 0-4,6"
  workflow_dispatch:

jobs:
  build:
    name: njfu library auto reserve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: build
        run: cargo build --release
      - name: login
        env:
          username: ${{secrets.NJFU_USERNAME}}
          password: ${{secrets.NJFU_PASSWORD}}
        run: cargo run --release login -u $username -p $password

      - name: reserve
        env:
          start: ${{vars.START}}
          end: ${{vars.END}}
          day: ${{vars.DAY}}
          filter: ${{vars.FILTER}}
        run: |
          date
          cargo run --release reserve -d $day -f $filter --start $start --end $end
