on:
  schedule:
    - cron: "${{env.CRON}}"

  workflow_dispatch:

jobs:
  build:
    name: njfu library auto reserve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: run
        run: |
          cargo run login -u ${{secrets.NJFUUSERNAME}} -p ${{secrets.NJFUPASSWORD}}
          cargo run reserve --day tomorrow --filter 4F-A --start ${{env.START}} --end ${{env.END}} -r 50
