on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: njfu library auto reserve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: build
        run: cargo build --release

      - name: openconnect
        env:
          username: ${{secrets.VPN_USERNAME}}
          password: ${{secrets.VPN_PASSWORD}}
          fingerprint: ${{secrets.FINGERPRINT}}
        run: |
          sudo apt install openconnect
          echo $password | sudo openconnect ocvpn.njfu.edu.cn -b --servercert $fingerprint -u $username --passwd-on-stdin

      - name: login
        env:
          NJFU_USERNAME: ${{secrets.NJFU_USERNAME}}
          NJFU_PASSWORD: ${{secrets.NJFU_PASSWORD}}
        run: cargo run --release login

      - name: check in
        run: cargo run --release in --all
