on:
  schedule:
    - cron: "0 23 * * 0-4,6"

jobs:
  build:
    name: njfu library auto reserve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: build
        run: cargo build --release
      - name: login
        env:
          username: ${{secrets.NJFU_USERNAME}}
          password: ${{secrets.NJFU_PASSWORD}}
        run: cargo run --release login -u $username -p $password

      - name: reserve
        env:
          start: ${{vars.START}}
          end: ${{vars.END}}
          day: ${{vars.DAY}}
          filter: ${{vars.FILTER}}
        run: |
          date
          end_h=$(echo $end | awk -F : 'print $1')
          end_m=$(echo $end | awk -F : 'print $2')

          if [ $(date "+%a") == Thu ]; \
          then \
            if (( $end_h > 20 )) || (( $end_h == 20 )) && (( $end_m > 0 )); \
            then \
              cargo run --release reserve -d $day -f $filter --start $start --end 20:00 \
            fi
          else \
            cargo run --release reserve -d $day -f $filter --start $start --end $end \
          fi
