on:
  schedule:
    - cron: "0 18 * * 1-6"

  workflow_dispatch:

jobs:
  build:
    name: njfu library auto reserve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: build
        run: cargo run --release
      - name: run
        run: |
          cargo run --release login -u ${{secrets.NJFUUSERNAME}} -p ${{secrets.NJFUPASSWORD}}
          cargo run --release reserve --filter 4F-A --start ${{vars.START}} --end ${{vars.END}} -r 50
